language: node_js
node_js:
  - '11'
cache:
  directories:
    - node_modules
addons:
  ssh_known_hosts: 116.203.146.153
before_install:
  - openssl aes-256-cbc -K $encrypted_146c3e4c94fa_key -iv $encrypted_146c3e4c94fa_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - cp deploy_rsa ~/.ssh/deploy_rsa
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist root@116.203.146.153:/root/test
  on:
    branch: development
